export default function EducationForm({ educationData, handleChange }) {
  return (
    <div>
      <form>
      <input
        type="text"
        id="school"
        onChange={handleChange}
        value={educationData.school}
      ></input>
      <input
        type="text"
        id="degree"
        onChange={handleChange}
        value={educationData.degree}
      ></input>
      <input
        type="date"
        id="startYear"
        onChange={handleChange}
        value={educationData.startYear}
      ></input>
      <input
        type="date"
        id="endYear"
        onChange={handleChange}
        value={educationData.endYear}
      ></input>
      <input
        type="number"
        id="gpa"
        onChange={handleChange}
        value={educationData.gpa}
      ></input>
        <button>Cancel</button>
        <button>Save</button>
        <button>Delete</button>
      </form>
    </div>
  );
}
