export default function EducationForm({ educationData, handleChange }) {
  return (
    <div>
      <input
        type="text"
        id="school"
        onChange={handleChange}
        value={educationData.school}
      ></input>
      <input
        type="text"
        id="degree"
        onChange={handleChange}
        value={educationData.degree}
      ></input>
      <input
        type="date"
        id="startYear"
        onChange={handleChange}
        value={educationData.startYear}
      ></input>
      <input
        type="date"
        id="end-year"
        onChange={handleChange}
        value={educationData.endYear}
      ></input>
      <input
        type="number"
        id="gpa"
        onChange={handleChange}
        value={educationData.gpa}
      ></input>
    </div>
  );
}
